// DESCRIPTION: Generates src/deno/embed.ts — raw imports of the Vite build so desktop
// bundles carry the assets in the compile VFS (no disk layout needed).
// USAGE: deno task embed  (after `bun run build`)

const ROOT = new URL("../", import.meta.url).pathname;

async function listDist(dir: string): Promise<string[]> {
	const out: string[] = [];
	try {
		for await (const e of Deno.readDir(`${ROOT}dist/${dir}`)) {
			const rel = `${dir}${e.name}`;
			if (e.isDirectory) out.push(...await listDist(`${rel}/`));
			else out.push(rel);
		}
	} catch {
		// no dist yet
	}
	return out;
}

const files = await listDist("");
if (!files.includes("index.html")) {
	console.error("gen-embed: dist/index.html missing — run `bun run build` first");
	Deno.exit(1);
}

const imports: string[] = [];
const entries: string[] = [];
files.sort().forEach((f, i) => {
	imports.push(`import a${i} from "../../dist/${f}" with { type: "bytes" };`);
	entries.push(`\t${JSON.stringify(f)}: a${i},`);
});

const src = `// AUTO-GENERATED by scripts/gen-embed.ts — do not edit. Regenerate with \`deno task embed\`.
${imports.join("\n")}

export const ASSETS: Record<string, Uint8Array> = {
${entries.join("\n")}
};
`;
await Deno.writeTextFile(`${ROOT}src/deno/embed.ts`, src);
console.log(`embed.ts: ${files.length} asset(s) embedded`);
