// AUTO-GENERATED by scripts/gen-embed.ts — do not edit. Regenerate with `deno task embed`.
import a0 from "../../dist/assets/App-CoTGx2ph.js" with { type: "bytes" };
import a1 from "../../dist/assets/index-DbOsApiZ.js" with { type: "bytes" };
import a2 from "../../dist/assets/index-jn8bOgcA.css" with { type: "bytes" };
import a3 from "../../dist/index.html" with { type: "bytes" };

export const ASSETS: Record<string, Uint8Array> = {
	"assets/App-CoTGx2ph.js": a0,
	"assets/index-DbOsApiZ.js": a1,
	"assets/index-jn8bOgcA.css": a2,
	"index.html": a3,
};
