// AUTO-GENERATED by scripts/gen-embed.ts — do not edit. Regenerate with `deno task embed`.
import a0 from "../../dist/assets/App-4Bb753D2.js" with { type: "bytes" };
import a1 from "../../dist/assets/index-MFaVcycy.css" with { type: "bytes" };
import a2 from "../../dist/assets/index-kHuMyUBj.js" with { type: "bytes" };
import a3 from "../../dist/index.html" with { type: "bytes" };

export const ASSETS: Record<string, Uint8Array> = {
	"assets/App-4Bb753D2.js": a0,
	"assets/index-MFaVcycy.css": a1,
	"assets/index-kHuMyUBj.js": a2,
	"index.html": a3,
};
